import math


ENERGIA_JUGADOR = 14
ENERGIA_DORMIR = math.ceil(ENERGIA_JUGADOR / 5)
MONEDAS_INICIALES = 5

# Se elige esta velocidad debido a que es el ancho de cada tile
VEL_MOVIMIENTO = 16

DURACION_DIA = 10
DURACION_ORO = 5
DURACION_LENA = 6

PIXELES_TILES = 16

PROB_ARBOL = 1
PROB_ORO = 1

DINERO_TRAMPA = 15000
